/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import TableModules.SaleModule;
import Utilities.TableService;
import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DanBroz
 */
public class Form_SaleInvoice extends javax.swing.JFrame implements Submitable {

    public Form_SaleInvoice() {

        initComponents();
        initialize();

        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.pack();
        saleModule_.fillEmployeeNameComboBox();
        dateChooser.setDate(new Date());
        dateChooser.setNextFocusableComponent(tableSaleItem);
        setColumProductTableWidth();
        setFeildValues();
        tableSaleItem.setColumnSelectionAllowed(true);
        tableSaleItem.setRowSelectionAllowed(true);

    }

    public JTable getAddSaleTable() {
        return tableSaleItem;
    }

    public void fillSaleItemTableRowWithProduct() {
        try {
            this.saleModule_.fetchProductDetailsToSaleItemTable();
            tableSaleItem.changeSelection(tableSaleItem.getSelectedRow(), 2, false, false);
        } catch (Exception ex) {

        }
    }

    public void fillCustomerDetailFields() {
        this.saleModule_.fetchCustomerDetailsToFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSaleItem = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        fieldTotal = new javax.swing.JTextField();
        fieldNetTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fieldDiscount = new javax.swing.JTextField();
        SubmitButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableEmployeeName = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        dateChooser = new com.toedter.calendar.JDateChooser();
        cboxEmployeeName = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        EmployeeAddButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        buttonEmployeeTableRefresh = new javax.swing.JButton();
        javax.swing.JButton buttonEmployeeTableDelete = new javax.swing.JButton();
        buttonSaleItemTableDelete = new javax.swing.JButton();
        buttonSaleItemTableRefresh = new javax.swing.JButton();
        buttonSaleItemTableAdd = new javax.swing.JButton();
        buttonUpdateCalculation = new javax.swing.JButton();
        fieldReceived = new javax.swing.JFormattedTextField();
        fieldCustomerID = new javax.swing.JFormattedTextField();
        fieldCustomerName = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        fieldAreaName = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        fieldSubAreaName = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Spot Sale");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setText("Customer ID");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Recevied");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setText("Net Total");

        tableSaleItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tableSaleItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Item ID", "Item Name", "Sold Qty", "Return Qty", "Rate", "Fix Disc/pc.", "extra Disc/pc.", "available"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableSaleItem.setRowHeight(25);
        tableSaleItem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tableSaleItemFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tableSaleItemFocusLost(evt);
            }
        });
        tableSaleItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSaleItemMouseClicked(evt);
            }
        });
        tableSaleItem.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                tableSaleItemComponentMoved(evt);
            }
        });
        tableSaleItem.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tableSaleItemPropertyChange(evt);
            }
        });
        tableSaleItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableSaleItemKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableSaleItem);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setText("Total");

        fieldTotal.setEditable(false);
        fieldTotal.setBackground(new java.awt.Color(0, 204, 102));
        fieldTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fieldTotal.setForeground(new java.awt.Color(255, 0, 0));
        fieldTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldTotalActionPerformed(evt);
            }
        });

        fieldNetTotal.setEditable(false);
        fieldNetTotal.setBackground(new java.awt.Color(0, 204, 102));
        fieldNetTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fieldNetTotal.setForeground(new java.awt.Color(255, 0, 0));
        fieldNetTotal.setToolTipText("");
        fieldNetTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNetTotalActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Discount");

        fieldDiscount.setEditable(false);
        fieldDiscount.setBackground(new java.awt.Color(51, 153, 255));
        fieldDiscount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fieldDiscount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldDiscountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldDiscountFocusLost(evt);
            }
        });
        fieldDiscount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldDiscountMouseClicked(evt);
            }
        });
        fieldDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDiscountActionPerformed(evt);
            }
        });
        fieldDiscount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldDiscountKeyPressed(evt);
            }
        });

        SubmitButton.setBackground(new java.awt.Color(0, 82, 82));
        SubmitButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        SubmitButton.setForeground(new java.awt.Color(255, 255, 255));
        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel6.setBackground(new java.awt.Color(255, 153, 153));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 26)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sale Invoice");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Submit a sale for a customer.");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_Sales.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel7.setText("Enter the sold and return quantities of each item for the selected party.");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Note: enter minimum details before submit.");

        tableEmployeeName.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Commision Holders"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableEmployeeName);

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setText("Date");

        dateChooser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dateChooserKeyPressed(evt);
            }
        });

        cboxEmployeeName.setEditable(true);

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel12.setText("Employee Name");

        EmployeeAddButton.setBackground(new java.awt.Color(0, 82, 82));
        EmployeeAddButton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        EmployeeAddButton.setForeground(new java.awt.Color(255, 255, 255));
        EmployeeAddButton.setText("Add");
        EmployeeAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeAddButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel8.setText("Add commision holders for this sale.");

        buttonEmployeeTableRefresh.setBackground(new java.awt.Color(0, 82, 82));
        buttonEmployeeTableRefresh.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        buttonEmployeeTableRefresh.setForeground(new java.awt.Color(255, 255, 255));
        buttonEmployeeTableRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttonIcon_refresh.png"))); // NOI18N
        buttonEmployeeTableRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEmployeeTableRefreshActionPerformed(evt);
            }
        });

        buttonEmployeeTableDelete.setBackground(new java.awt.Color(255, 0, 0));
        buttonEmployeeTableDelete.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        buttonEmployeeTableDelete.setForeground(new java.awt.Color(255, 255, 255));
        buttonEmployeeTableDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEmployeeTableDeleteActionPerformed(evt);
            }
        });

        buttonSaleItemTableDelete.setBackground(new java.awt.Color(255, 0, 0));
        buttonSaleItemTableDelete.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        buttonSaleItemTableDelete.setForeground(new java.awt.Color(255, 255, 255));
        buttonSaleItemTableDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaleItemTableDeleteActionPerformed(evt);
            }
        });

        buttonSaleItemTableRefresh.setBackground(new java.awt.Color(0, 82, 82));
        buttonSaleItemTableRefresh.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        buttonSaleItemTableRefresh.setForeground(new java.awt.Color(255, 255, 255));
        buttonSaleItemTableRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttonIcon_refresh.png"))); // NOI18N
        buttonSaleItemTableRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaleItemTableRefreshActionPerformed(evt);
            }
        });

        buttonSaleItemTableAdd.setBackground(new java.awt.Color(0, 82, 82));
        buttonSaleItemTableAdd.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        buttonSaleItemTableAdd.setForeground(new java.awt.Color(255, 255, 255));
        buttonSaleItemTableAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttonIcon_plus.png"))); // NOI18N
        buttonSaleItemTableAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaleItemTableAddActionPerformed(evt);
            }
        });

        buttonUpdateCalculation.setBackground(new java.awt.Color(0, 82, 82));
        buttonUpdateCalculation.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        buttonUpdateCalculation.setForeground(new java.awt.Color(255, 255, 255));
        buttonUpdateCalculation.setText("Update Calculation");
        buttonUpdateCalculation.setToolTipText("");
        buttonUpdateCalculation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateCalculationActionPerformed(evt);
            }
        });

        fieldReceived.setBackground(new java.awt.Color(51, 153, 255));
        fieldReceived.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.0"))));
        fieldReceived.setToolTipText("");
        fieldReceived.setAutoscrolls(false);
        fieldReceived.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        fieldCustomerID.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        fieldCustomerID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fieldCustomerID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldCustomerIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldCustomerIDFocusLost(evt);
            }
        });
        fieldCustomerID.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fieldCustomerIDPropertyChange(evt);
            }
        });
        fieldCustomerID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldCustomerIDKeyPressed(evt);
            }
        });

        fieldCustomerName.setEditable(false);
        fieldCustomerName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setText("Customer Name");

        fieldAreaName.setEditable(false);
        fieldAreaName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel14.setText("Area");

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setText("Sub Area");

        fieldSubAreaName.setEditable(false);
        fieldSubAreaName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fieldSubAreaName, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fieldAreaName, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonSaleItemTableAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonSaleItemTableDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonSaleItemTableRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldDiscount)
                                    .addComponent(fieldReceived, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(236, 236, 236)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fieldNetTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel9)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonUpdateCalculation, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboxEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(buttonEmployeeTableDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonEmployeeTableRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(EmployeeAddButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fieldAreaName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(fieldCustomerID))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(fieldSubAreaName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonSaleItemTableRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(buttonEmployeeTableRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonEmployeeTableDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(buttonSaleItemTableAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(buttonSaleItemTableDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cboxEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(EmployeeAddButton)
                            .addGap(80, 80, 80))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fieldNetTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonUpdateCalculation, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel9)
                            .addGap(14, 14, 14)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldReceived, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addContainerGap())))
        );

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Save");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Select Customer");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Update Calculation");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void initialize() {

        saleModule_ = new SaleModule(tableSaleItem, tableEmployeeName, fieldCustomerID, fieldCustomerName, fieldAreaName, fieldSubAreaName,
                cboxEmployeeName, dateChooser, fieldDiscount, fieldReceived, fieldTotal, fieldNetTotal);
        tableModelEmployeeNameTable_ = (DefaultTableModel) tableEmployeeName.getModel();
        tableModelSaleItemTable_ = (DefaultTableModel) tableSaleItem.getModel();

    }

    private void TABKeyPressNameColumn() {
        if (tableSaleItem.getValueAt(tableSaleItem.getSelectedRow(), COLUMN_ITEM_ID) != null) {
            try {
                saleModule_.fetchProductDetailsToSaleItemTable();
            } catch (Exception ex) {

            }
        }
    }

    private void TABKeyPressRQtyColumn() {
        tableSaleItem.changeSelection(tableSaleItem.getSelectedRow(), COLUMN_EXTRA_DISC - 1, false, false);
    }

    private void TABKeyPressExtraDiscColumn() {
        if (tableSaleItem.getValueAt(tableSaleItem.getSelectedRow(), COLUMN_ITEM_ID) != null) {

            if (tableSaleItem.getSelectedRow() == tableSaleItem.getRowCount() - 1) {
                tableModelSaleItemTable_.addRow(new Object[]{null, null, null, null, null, null, null, null});
            }
            tableSaleItem.changeSelection(tableSaleItem.getSelectedRow(), COLUMN_AVAILABLE, false, false);
        } else {
            tableSaleItem.changeSelection(tableSaleItem.getSelectedRow(), 0, false, false);
        }
    }

    private void validateFormData() {
        tableSaleItem.clearSelection();
        TableService.setValueToEmptyColumn(tableModelSaleItemTable_, COLUMN_SOLD_QTY, 0);
        TableService.setValueToEmptyColumn(tableModelSaleItemTable_, COLUMN_REPLACE, 0);
        TableService.setValueToEmptyColumn(tableModelSaleItemTable_, COLUMN_EXTRA_DISC, 0.0);
        TableService.setValueToEmptyColumn(tableModelSaleItemTable_, COLUMN_FIXED_DISC, 0.0);
        TableService.deleteRowWithEmptyColumn(tableModelSaleItemTable_, COLUMN_ITEM_ID);
        TableService.deleteRowWithColumnsValue(tableModelSaleItemTable_, new int[]{COLUMN_SOLD_QTY, COLUMN_REPLACE}, 0);
        if (fieldReceived.getText().equals("")) {
            fieldReceived.setText(String.valueOf(0.0));
        }
    }

    private void setColumProductTableWidth() {
        tableSaleItem.getColumnModel().getColumn(COLUMN_ITEM_ID).setPreferredWidth(20);
        tableSaleItem.getColumnModel().getColumn(COLUMN_ITEM_NAME).setPreferredWidth(100);
        tableSaleItem.getColumnModel().getColumn(COLUMN_SOLD_QTY).setPreferredWidth(30);
        tableSaleItem.getColumnModel().getColumn(COLUMN_REPLACE).setPreferredWidth(30);
        tableSaleItem.getColumnModel().getColumn(COLUMN_RATE).setPreferredWidth(30);
        tableSaleItem.getColumnModel().getColumn(COLUMN_FIXED_DISC).setPreferredWidth(30);
        tableSaleItem.getColumnModel().getColumn(COLUMN_EXTRA_DISC).setPreferredWidth(30);
        tableSaleItem.getColumnModel().getColumn(COLUMN_AVAILABLE).setPreferredWidth(30);

    }

    @Override
    public void submitAction() {
        saleModule_.submitSale();
    }

    public void setEnableParent() {
        this.setEnabled(true);
    }

    private void submit() {

        validateFormData();
        updateCalculations();

        if (!TableService.isTableEmpty(tableSaleItem)
                && !TableService.isTableEmpty(tableEmployeeName)
                && !fieldCustomerID.getText().equals("")
                && !fieldCustomerName.getText().equals("")
                && !fieldAreaName.getText().equals("")
                && !fieldSubAreaName.getText().equals("")) {

            double netValue;
            netValue = Double.valueOf(this.fieldNetTotal.getText());

            if (netValue >= 0) {
                new Form_SubmitWarning(this, "Sale").setVisible(true);
                this.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(null, "Received Amount is greater thn NetAmount!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Incomplete Details");
        }
    }
    private void fieldTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldTotalActionPerformed

    private void tableSaleItemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableSaleItemKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SHIFT && tableSaleItem.getSelectedColumn() == COLUMN_ITEM_ID) {
            new Form_ProductSeletionView(this, tableSaleItem).setVisible(true);
            this.setEnabled(false);
        }
        if (evt.getKeyCode() == KeyEvent.VK_TAB) {

            //for R.Qty column
            if (tableSaleItem.getSelectedColumn() == COLUMN_REPLACE) {
                TABKeyPressRQtyColumn();
            }
            //for Name Column
            if (tableSaleItem.getSelectedColumn() == COLUMN_ITEM_NAME) {
                TABKeyPressNameColumn();
            }
            if (tableSaleItem.getSelectedColumn() == COLUMN_EXTRA_DISC) {
                TABKeyPressExtraDiscColumn();
            }
        }
        if (evt.getKeyCode() == KeyEvent.VK_R) {
            this.fieldReceived.setText("");
            this.fieldReceived.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_C) {
            this.fieldCustomerID.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_U) {
            tableSaleItem.changeSelection(0, 1, false, false);
            validateFormData();
            updateCalculations();
        }


    }//GEN-LAST:event_tableSaleItemKeyPressed

    private void tableSaleItemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tableSaleItemFocusGained


    }//GEN-LAST:event_tableSaleItemFocusGained

    private void tableSaleItemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tableSaleItemFocusLost


    }//GEN-LAST:event_tableSaleItemFocusLost

    private void tableSaleItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSaleItemMouseClicked

    }//GEN-LAST:event_tableSaleItemMouseClicked

    private void fieldDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDiscountActionPerformed

    }//GEN-LAST:event_fieldDiscountActionPerformed

    private void fieldDiscountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldDiscountKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SHIFT) {
            this.tableSaleItem.requestFocus();
        }
    }//GEN-LAST:event_fieldDiscountKeyPressed

    private void fieldDiscountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldDiscountFocusLost

    }//GEN-LAST:event_fieldDiscountFocusLost

    private void fieldDiscountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldDiscountFocusGained

    }//GEN-LAST:event_fieldDiscountFocusGained

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        submit();
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        jPanel1.requestFocus();
    }//GEN-LAST:event_jPanel1MouseClicked

    private void fieldDiscountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldDiscountMouseClicked

    }//GEN-LAST:event_fieldDiscountMouseClicked

    private void fieldNetTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNetTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNetTotalActionPerformed

    private void tableSaleItemComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tableSaleItemComponentMoved

    }//GEN-LAST:event_tableSaleItemComponentMoved

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SHIFT) {
            this.tableSaleItem.requestFocus();
        }
    }//GEN-LAST:event_jPanel1KeyPressed

    private void EmployeeAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeAddButtonActionPerformed
        boolean isEmployeeNamePresent = TableService.isValuePresent(tableModelEmployeeNameTable_, cboxEmployeeName.getSelectedItem().toString());
        if (!isEmployeeNamePresent) {
            tableModelEmployeeNameTable_.addRow(new Object[]{cboxEmployeeName.getSelectedItem().toString()});
        }

    }//GEN-LAST:event_EmployeeAddButtonActionPerformed

    private void buttonEmployeeTableRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEmployeeTableRefreshActionPerformed
        TableService.deleteAllRows(tableModelEmployeeNameTable_);
    }//GEN-LAST:event_buttonEmployeeTableRefreshActionPerformed

    private void buttonEmployeeTableDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEmployeeTableDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEmployeeTableDeleteActionPerformed

    private void tableSaleItemPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tableSaleItemPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tableSaleItemPropertyChange

    private void buttonSaleItemTableDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaleItemTableDeleteActionPerformed
        TableService.deleteSelectedRows(tableSaleItem);
    }//GEN-LAST:event_buttonSaleItemTableDeleteActionPerformed

    private void buttonSaleItemTableRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaleItemTableRefreshActionPerformed
        TableService.deleteAllRows(tableModelSaleItemTable_);
        tableModelSaleItemTable_.addRow(new Object[]{null, null, null, null, null, null, null, null});
    }//GEN-LAST:event_buttonSaleItemTableRefreshActionPerformed

    private void buttonSaleItemTableAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaleItemTableAddActionPerformed
        tableModelSaleItemTable_.addRow(new Object[]{null, null, null, null, null, null, null, null});
    }//GEN-LAST:event_buttonSaleItemTableAddActionPerformed

    private void buttonUpdateCalculationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateCalculationActionPerformed
        // TODO add your handling code here:
        tableSaleItem.changeSelection(0, 1, false, false);
        validateFormData();
        updateCalculations();
    }//GEN-LAST:event_buttonUpdateCalculationActionPerformed

    private void dateChooserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateChooserKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateChooserKeyPressed

    private void fieldCustomerIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldCustomerIDKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_SHIFT) {
            new Form_CustomerSelectionView(this, this.fieldCustomerID, this.fieldCustomerName, this.fieldAreaName, this.fieldSubAreaName).setVisible(true);
            this.setEnabled(false);
        }
    }//GEN-LAST:event_fieldCustomerIDKeyPressed

    private void fieldCustomerIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldCustomerIDFocusGained

    }//GEN-LAST:event_fieldCustomerIDFocusGained

    private void fieldCustomerIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldCustomerIDFocusLost
        // TODO add your handling code here:
        fillCustomerDetailFields();
        tableSaleItem.requestFocus();
    }//GEN-LAST:event_fieldCustomerIDFocusLost

    private void fieldCustomerIDPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fieldCustomerIDPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCustomerIDPropertyChange

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.fieldCustomerID.requestFocus();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        submit();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void updateCalculations() {

        double totalValue = 0;
        double discountValue = 0;
        double receivedValue = 0;
        int soldQuantity;
        double rate;
        double fixedDiscount;
        double extraDiscount;

        for (int i = 0; i < tableSaleItem.getRowCount(); i++) {
            soldQuantity = (int) tableModelSaleItemTable_.getValueAt(i, COLUMN_SOLD_QTY);
            rate = (double) tableModelSaleItemTable_.getValueAt(i, COLUMN_RATE);
            fixedDiscount = (double) tableModelSaleItemTable_.getValueAt(i, COLUMN_FIXED_DISC);
            extraDiscount = (double) tableModelSaleItemTable_.getValueAt(i, COLUMN_EXTRA_DISC);
            totalValue += soldQuantity * rate;
            discountValue += soldQuantity * (fixedDiscount + extraDiscount);
        }
        if (!fieldReceived.getText().equals("")) {
            receivedValue = Double.valueOf(fieldReceived.getText());
        }
        fieldTotal.setText(Double.toString(totalValue));
        fieldDiscount.setText(Double.toString(discountValue));
        fieldNetTotal.setText(Double.toString(totalValue - discountValue - receivedValue));
    }

    private void setFeildValues() {

        if (fieldDiscount.getText().equals("") || fieldDiscount.getText().equals("0")) {
            fieldDiscount.setText("0.0");
        }
        if (fieldNetTotal.getText().equals("") || fieldNetTotal.getText().equals("0")) {
            fieldNetTotal.setText("0.0");
        }
        if (fieldTotal.getText().equals("") || fieldTotal.getText().equals("0")) {
            fieldTotal.setText("0.0");
        }
    }

    private SaleModule saleModule_;
    DefaultTableModel tableModelEmployeeNameTable_;
    DefaultTableModel tableModelSaleItemTable_;

    public static final int COLUMN_ITEM_ID = 0;
    public static final int COLUMN_ITEM_NAME = 1;
    public static final int COLUMN_SOLD_QTY = 2;
    public static final int COLUMN_REPLACE = 3;
    public static final int COLUMN_RATE = 4;
    public static final int COLUMN_FIXED_DISC = 5;
    public static final int COLUMN_EXTRA_DISC = 6;
    public static final int COLUMN_AVAILABLE = 7;

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_SaleInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_SaleInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_SaleInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_SaleInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_SaleInvoice().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EmployeeAddButton;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JButton buttonEmployeeTableRefresh;
    private javax.swing.JButton buttonSaleItemTableAdd;
    private javax.swing.JButton buttonSaleItemTableDelete;
    private javax.swing.JButton buttonSaleItemTableRefresh;
    private javax.swing.JButton buttonUpdateCalculation;
    private javax.swing.JComboBox<String> cboxEmployeeName;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JTextField fieldAreaName;
    private javax.swing.JFormattedTextField fieldCustomerID;
    private javax.swing.JTextField fieldCustomerName;
    private javax.swing.JTextField fieldDiscount;
    private javax.swing.JTextField fieldNetTotal;
    private javax.swing.JFormattedTextField fieldReceived;
    private javax.swing.JTextField fieldSubAreaName;
    private javax.swing.JTextField fieldTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableEmployeeName;
    private javax.swing.JTable tableSaleItem;
    // End of variables declaration//GEN-END:variables
}
