/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import static Forms.Form_SaleInvoice.COLUMN_SOLD_QTY;
import TableModules.PurchaseModule;
import Utilities.TableService;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL PC
 */
public class Form_PurchaseInvoice extends javax.swing.JFrame implements Submitable {

    public Form_PurchaseInvoice() {

        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.pack();
        
        tableModelPurchaseItemTable_ = (DefaultTableModel) tablePurchaseItem.getModel();
        purchaseModule_ = PurchaseModule.getInstance();
        dateChooser.setDate(new Date());        
        purchaseModule_.fillVendorCbox(cboxVendorName);
        setColumProductTableWidth();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePurchaseItem = new javax.swing.JTable();
        fieldAmount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        buttonSubmit = new javax.swing.JButton();
        cboxVendorName = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dateChooser = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        buttonSubmit1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        tablePurchaseItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tablePurchaseItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Purchased Qty", "Replace", "Rate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePurchaseItem.setFocusTraversalPolicyProvider(true);
        tablePurchaseItem.setRowHeight(25);
        tablePurchaseItem.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablePurchaseItem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tablePurchaseItemFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tablePurchaseItemFocusLost(evt);
            }
        });
        tablePurchaseItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePurchaseItemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePurchaseItem);

        fieldAmount.setEditable(false);
        fieldAmount.setBackground(new java.awt.Color(0, 204, 102));
        fieldAmount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fieldAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAmountActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Total");

        buttonSubmit.setBackground(new java.awt.Color(0, 102, 0));
        buttonSubmit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonSubmit.setForeground(new java.awt.Color(255, 255, 255));
        buttonSubmit.setText("Submit");
        buttonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubmitActionPerformed(evt);
            }
        });

        cboxVendorName.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cboxVendorName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboxVendorNameItemStateChanged(evt);
            }
        });
        cboxVendorName.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cboxVendorNameMouseMoved(evt);
            }
        });
        cboxVendorName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cboxVendorNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cboxVendorNameFocusLost(evt);
            }
        });
        cboxVendorName.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cboxVendorNamePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cboxVendorName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboxVendorNameMouseClicked(evt);
            }
        });
        cboxVendorName.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                cboxVendorNameInputMethodTextChanged(evt);
            }
        });
        cboxVendorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxVendorNameActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setText("Vendor");

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Purchase Invoice");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Submit a purchase from a vendor");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        dateChooser.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setText("Date");

        buttonSubmit1.setBackground(new java.awt.Color(0, 102, 0));
        buttonSubmit1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonSubmit1.setForeground(new java.awt.Color(255, 255, 255));
        buttonSubmit1.setText("Update Calculations");
        buttonSubmit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubmit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboxVendorName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                        .addComponent(buttonSubmit1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboxVendorName, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSubmit1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void validatePurchaseItemTable() {
        TableService.setValueToEmptyColumn(tableModelPurchaseItemTable_, COLUMN_SOLD_QTY, 0);
        TableService.setValueToEmptyColumn(tableModelPurchaseItemTable_, COLUMN_REPLACE, 0);
        TableService.deleteRowWithColumnsValue(tableModelPurchaseItemTable_, new int[]{COLUMN_SOLD_QTY, COLUMN_REPLACE}, 0);
    }

    private void setColumProductTableWidth() {
        tablePurchaseItem.getColumnModel().getColumn(COLUMN_ITEM_ID).setPreferredWidth(20);
        tablePurchaseItem.getColumnModel().getColumn(COLUMN_ITEM_NAME).setPreferredWidth(100);
        tablePurchaseItem.getColumnModel().getColumn(COLUMN_SOLD_QTY).setPreferredWidth(30);
        tablePurchaseItem.getColumnModel().getColumn(COLUMN_REPLACE).setPreferredWidth(30);
        tablePurchaseItem.getColumnModel().getColumn(COLUMN_RATE).setPreferredWidth(30);
    }

    private void updateCalculations() {
        double total = 0;
        for (int i = 0; i < tablePurchaseItem.getRowCount(); i++) {
            if (tablePurchaseItem.getModel().getValueAt(i, 2) != null && tablePurchaseItem.getModel().getValueAt(i, 4) != null) {
                total = total + (double) ((int) tablePurchaseItem.getModel().getValueAt(i, COLUMN_PURCHASE_QTY) * (double) tablePurchaseItem.getModel().getValueAt(i, 4));
            }
        }

        fieldAmount.setText(Double.toString(total));
    }

    private void resetComponents() {

        TableService.deleteAllRows(tableModelPurchaseItemTable_);
        updateCalculations();
    }

    @Override
    public void submitAction() {
        double amount = Double.valueOf(this.fieldAmount.getText());
        Date purchaseDate = this.dateChooser.getDate();
        String vendorName = this.cboxVendorName.getSelectedItem().toString();

        purchaseModule_.submitPurchase(tablePurchaseItem, amount, purchaseDate, vendorName);
        resetComponents();

    }

    @Override
    public void setEnableParent() {
        this.setEnabled(true);
    }

    private void buttonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitActionPerformed
        
        validatePurchaseItemTable();
        updateCalculations();
        
        if (!TableService.isTableEmpty(tablePurchaseItem)
                && !(this.cboxVendorName.getSelectedIndex() == -1)
                && !this.fieldAmount.getText().equals("")) {
            

            new Form_SubmitWarning(this, "Purchase").setVisible(true);
            this.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, "Incomplete Details");
        }


    }//GEN-LAST:event_buttonSubmitActionPerformed

    private void fieldAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAmountActionPerformed


    }//GEN-LAST:event_fieldAmountActionPerformed

    private void tablePurchaseItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePurchaseItemMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tablePurchaseItemMouseClicked

    private void cboxVendorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxVendorNameActionPerformed
    }//GEN-LAST:event_cboxVendorNameActionPerformed

    private void cboxVendorNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cboxVendorNameFocusGained


    }//GEN-LAST:event_cboxVendorNameFocusGained

    private void cboxVendorNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cboxVendorNameFocusLost


    }//GEN-LAST:event_cboxVendorNameFocusLost

    private void cboxVendorNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboxVendorNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxVendorNameMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        jPanel1.requestFocus();
    }//GEN-LAST:event_jPanel1MouseClicked

    private void cboxVendorNameMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboxVendorNameMouseMoved

    }//GEN-LAST:event_cboxVendorNameMouseMoved

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved

    }//GEN-LAST:event_jPanel1MouseMoved

    private void tablePurchaseItemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tablePurchaseItemFocusGained

        updateCalculations();

    }//GEN-LAST:event_tablePurchaseItemFocusGained

    private void tablePurchaseItemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tablePurchaseItemFocusLost
        updateCalculations();
    }//GEN-LAST:event_tablePurchaseItemFocusLost

    private void cboxVendorNameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cboxVendorNameInputMethodTextChanged

    }//GEN-LAST:event_cboxVendorNameInputMethodTextChanged

    private void cboxVendorNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboxVendorNameItemStateChanged

    }//GEN-LAST:event_cboxVendorNameItemStateChanged

    private void cboxVendorNamePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cboxVendorNamePopupMenuWillBecomeInvisible
        this.purchaseModule_.fetchProductDetailsToPurchaseItemTable(cboxVendorName.getSelectedItem().toString(), tablePurchaseItem);

    }//GEN-LAST:event_cboxVendorNamePopupMenuWillBecomeInvisible

    private void buttonSubmit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmit1ActionPerformed
        // TODO add your handling code here:
        validatePurchaseItemTable();
        updateCalculations();
    }//GEN-LAST:event_buttonSubmit1ActionPerformed

    public static final int COLUMN_ITEM_ID = 0;
    public static final int COLUMN_ITEM_NAME = 1;
    public static final int COLUMN_PURCHASE_QTY = 2;
    public static final int COLUMN_REPLACE = 3;
    public static final int COLUMN_RATE = 4;

    private DefaultTableModel tableModelPurchaseItemTable_;
    private PurchaseModule purchaseModule_;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_PurchaseInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_PurchaseInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_PurchaseInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_PurchaseInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_PurchaseInvoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSubmit;
    private javax.swing.JButton buttonSubmit1;
    private javax.swing.JComboBox cboxVendorName;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JTextField fieldAmount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePurchaseItem;
    // End of variables declaration//GEN-END:variables

}
