/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import DataGateway.CustomerDataGateway;
import TableModules.AreaModule;
import TableModules.CustomerModule;
import Utilities.TableService;
import com.sun.glass.events.KeyEvent;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author DanBroz
 */
public class Form_CustomerDetails extends javax.swing.JFrame implements Submitable {

    /**
     * Creates new form CustomerDetailsForm
     */
    public Form_CustomerDetails() {

        initialize(null, null);
        initComponents();
        decorateAreaComboBox();
    }

    public Form_CustomerDetails(Form_Customers parentForm, JTable customerTable) {

        initialize(parentForm, customerTable);
        initComponents();
        decorateAreaComboBox();
        decorateSubAreaComboBox(cboxArea.getSelectedItem().toString());
        tableModelProductDiscountTable_ = (DefaultTableModel) this.tableProductDiscount.getModel();
        this.fieldName.setNextFocusableComponent(this.fieldCont1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cusDetailPanel = new javax.swing.JPanel();
        labelArea = new javax.swing.JLabel();
        labelCont2 = new javax.swing.JLabel();
        labelCont1 = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        fieldName = new javax.swing.JTextField();
        cboxArea = new javax.swing.JComboBox<>();
        fieldCont1 = new javax.swing.JFormattedTextField();
        fieldCont2 = new javax.swing.JFormattedTextField();
        cboxSubArea = new javax.swing.JComboBox<>();
        labelArea1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProductDiscount = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        submitbutton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cusNLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Info");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        cusDetailPanel.setBackground(new java.awt.Color(255, 255, 255));

        labelArea.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labelArea.setText("Area");

        labelCont2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labelCont2.setText("Cont#2");

        labelCont1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labelCont1.setText("Cont#1");

        labelName.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labelName.setText("Name");

        fieldName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldNameKeyPressed(evt);
            }
        });

        cboxArea.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboxAreaItemStateChanged(evt);
            }
        });
        cboxArea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cboxAreaFocusLost(evt);
            }
        });
        cboxArea.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cboxAreaPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cboxArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxAreaActionPerformed(evt);
            }
        });
        cboxArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboxAreaKeyPressed(evt);
            }
        });

        try {
            fieldCont1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fieldCont1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCont1ActionPerformed(evt);
            }
        });

        try {
            fieldCont2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fieldCont2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCont2ActionPerformed(evt);
            }
        });

        cboxSubArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxSubAreaActionPerformed(evt);
            }
        });
        cboxSubArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboxSubAreaKeyPressed(evt);
            }
        });

        labelArea1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labelArea1.setText("Sub Area");

        tableProductDiscount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Product ID", "Discount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableProductDiscount);

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttonIcon_plus.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cusDetailPanelLayout = new javax.swing.GroupLayout(cusDetailPanel);
        cusDetailPanel.setLayout(cusDetailPanelLayout);
        cusDetailPanelLayout.setHorizontalGroup(
            cusDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cusDetailPanelLayout.createSequentialGroup()
                .addGroup(cusDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cusDetailPanelLayout.createSequentialGroup()
                        .addGroup(cusDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelArea)
                            .addGroup(cusDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(cusDetailPanelLayout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addGroup(cusDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelCont1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(labelName, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cusDetailPanelLayout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addComponent(labelCont2)))
                            .addComponent(labelArea1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cusDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cboxSubArea, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboxArea, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fieldName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldCont1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                            .addComponent(fieldCont2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        cusDetailPanelLayout.setVerticalGroup(
            cusDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cusDetailPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cusDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cusDetailPanelLayout.createSequentialGroup()
                        .addGroup(cusDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelName)
                            .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cusDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCont1)
                            .addComponent(fieldCont1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cusDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldCont2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCont2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cusDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelArea)
                            .addComponent(cboxArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cusDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelArea1)
                            .addComponent(cboxSubArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        submitbutton.setBackground(new java.awt.Color(0, 82, 82));
        submitbutton.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        submitbutton.setForeground(new java.awt.Color(255, 255, 255));
        submitbutton.setText("Submit");
        submitbutton.setBorder(null);
        submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbuttonActionPerformed(evt);
            }
        });
        submitbutton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                submitbuttonKeyPressed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter Details");

        cusNLabel1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        cusNLabel1.setForeground(new java.awt.Color(255, 255, 255));
        cusNLabel1.setText("Fill the details below and click the submit button.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(cusNLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cusNLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cusDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(submitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cusDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void initialize(Form_Customers parentForm, JTable customerTable) {
        this.parentForm_ = parentForm;
        this.customerTable_ = customerTable;
        this.customerModule_ = CustomerModule.getInstance();
        this.areaModule_ = AreaModule.getInstance();
    }

    private void decorateAreaComboBox() {
        customerModule_.fillAreaComboBox(this.cboxArea);
    }

    private void decorateSubAreaComboBox(String areaName) {
        cboxSubArea.removeAllItems();
        customerModule_.fillSubAreaComboBox(this.cboxSubArea, areaName);
        cboxSubArea.setSelectedIndex(-1);

    }

    private void clearAllFields() {
        fieldName.setText("");
        fieldCont1.setText("");
        fieldCont2.setText("");
        cboxArea.setSelectedIndex(-1);
        cboxSubArea.setSelectedIndex(-1);
    }

    private void validateProductDiscountTable() {
        TableService.deleteRowWithEmptyColumn(tableModelProductDiscountTable_, 0);
        TableService.deleteRowWithEmptyColumn(tableModelProductDiscountTable_, 1);
    }

    @Override
    public void setEnableParent() {
        this.setEnabled(true);
    }

    @Override
    public void submitAction() {

        int areaID = customerModule_.getAreaId(cboxArea.getSelectedItem().toString());
        int subAreaID = customerModule_.getSubAreaId(cboxSubArea.getSelectedItem().toString());

        customerModule_.submit(fieldName.getText(), fieldCont1.getText(), fieldCont2.getText(),
                String.valueOf(areaID), String.valueOf(subAreaID));

        for (int i = 0; i < tableProductDiscount.getRowCount(); i++) {
            int customerID = customerModule_.getLastCustomerID();
            customerModule_.submitCustomerProductDiscount(customerID,
                    Integer.valueOf(tableProductDiscount.getValueAt(i, 0).toString()),
                    Double.valueOf(tableProductDiscount.getValueAt(i, 1).toString()));
        }
        
        clearAllFields();
        TableService.deleteAllRows(tableModelProductDiscountTable_);
        TableService.deleteAllRows((DefaultTableModel) customerTable_.getModel());
        customerModule_.fillCustomerTable(customerTable_);
        parentForm_.setCustomerTableColumnWidth();
    }

    private void submit() {
        validateProductDiscountTable();
        if ("".equals(fieldName.getText())
                || cboxArea.getSelectedIndex() == -1
                || cboxSubArea.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Details Not Compeletly Filled");
        } else {
            new Form_SubmitWarning(this, "Customer").setVisible(true);
            this.setEnabled(false);
        }
    }


    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        parentForm_.setEnabled(true);
        parentForm_.toFront();
    }//GEN-LAST:event_formWindowClosed

    private void submitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbuttonActionPerformed
        submit();
    }//GEN-LAST:event_submitbuttonActionPerformed

    private void cboxAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxAreaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cboxAreaActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed


    }//GEN-LAST:event_formKeyPressed

    private void submitbuttonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_submitbuttonKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            submit();
        }
    }//GEN-LAST:event_submitbuttonKeyPressed

    private void cboxAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboxAreaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            submitbutton.requestFocus();
        }

    }//GEN-LAST:event_cboxAreaKeyPressed

    private void fieldNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldNameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            fieldCont1.requestFocus();
        }
    }//GEN-LAST:event_fieldNameKeyPressed

    private void fieldCont1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCont1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCont1ActionPerformed

    private void fieldCont2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCont2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCont2ActionPerformed

    private void cboxSubAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxSubAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxSubAreaActionPerformed

    private void cboxSubAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboxSubAreaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxSubAreaKeyPressed

    private void cboxAreaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboxAreaItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_cboxAreaItemStateChanged

    private void cboxAreaPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cboxAreaPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        decorateSubAreaComboBox(cboxArea.getSelectedItem().toString());
    }//GEN-LAST:event_cboxAreaPopupMenuWillBecomeInvisible

    private void cboxAreaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cboxAreaFocusLost
        // TODO add your handling code here:
        decorateSubAreaComboBox(cboxArea.getSelectedItem().toString());
    }//GEN-LAST:event_cboxAreaFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        tableModelProductDiscountTable_.addRow(new Object[]{null, null});
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_CustomerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_CustomerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_CustomerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_CustomerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_CustomerDetails().setVisible(true);
            }
        });
    }

    Form_Customers parentForm_;
    JTable customerTable_;
    private CustomerModule customerModule_;
    private AreaModule areaModule_;
    private DefaultTableModel tableModelProductDiscountTable_;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboxArea;
    private javax.swing.JComboBox<String> cboxSubArea;
    private javax.swing.JPanel cusDetailPanel;
    private javax.swing.JLabel cusNLabel1;
    private javax.swing.JFormattedTextField fieldCont1;
    private javax.swing.JFormattedTextField fieldCont2;
    private javax.swing.JTextField fieldName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelArea;
    private javax.swing.JLabel labelArea1;
    private javax.swing.JLabel labelCont1;
    private javax.swing.JLabel labelCont2;
    private javax.swing.JLabel labelName;
    private javax.swing.JButton submitbutton;
    private javax.swing.JTable tableProductDiscount;
    // End of variables declaration//GEN-END:variables
}
