/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;
import TableModules.Authentication;
import com.sun.glass.events.KeyEvent;
import java.awt.Toolkit;
import javafx.scene.paint.Color;
import static javax.swing.BorderFactory.createEmptyBorder;
import javax.swing.border.LineBorder;




/*
 * @author DanBroz
 */


public class Form_Login extends javax.swing.JFrame {
       
   
    Authentication authentication_;
   // RunLogin Rlogin = new RunLogin(this); 
    Form_Home homeForm_ ;
   

       
    public Form_Login() {
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("formIcon_Login.png")));
        
        initComponents();
        
        authentication_ = Authentication.getInstance();
        homeForm_ = new Form_Home();
       
       
       
    }
 
    /**
     * 
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        LoginPanel = new javax.swing.JPanel();
        UnameLabel = new javax.swing.JLabel();
        PassLebel = new javax.swing.JLabel();
        UnameField = new javax.swing.JTextField();
        PassField = new javax.swing.JPasswordField();
        UErrorField = new javax.swing.JLabel();
        PErrorField = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        warning = new javax.swing.JLabel();
        loginbutton = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(249, 243, 42));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(337, 151));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.setToolTipText("");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(0, 204, 51));
        jPanel3.setToolTipText("");

        LoginPanel.setBackground(new java.awt.Color(255, 255, 255));
        LoginPanel.setToolTipText("");

        UnameLabel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        UnameLabel.setText("USER NAME");

        PassLebel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        PassLebel.setText("PASSWORD");

        UnameField.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        UnameField.setToolTipText("");
        UnameField.setBorder(null);
        UnameField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        UnameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UnameFieldFocusGained(evt);
            }
        });
        UnameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UnameFieldMouseClicked(evt);
            }
        });
        UnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnameFieldActionPerformed(evt);
            }
        });
        UnameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UnameFieldKeyPressed(evt);
            }
        });

        PassField.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        PassField.setToolTipText("");
        PassField.setBorder(null);
        PassField.setNextFocusableComponent(loginbutton);
        PassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassFieldActionPerformed(evt);
            }
        });
        PassField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PassFieldKeyPressed(evt);
            }
        });

        UErrorField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        UErrorField.setForeground(new java.awt.Color(255, 0, 0));
        UErrorField.setToolTipText("");

        PErrorField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PErrorField.setForeground(new java.awt.Color(255, 0, 0));
        PErrorField.setToolTipText("");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        warning.setBackground(new java.awt.Color(255, 51, 51));
        warning.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        warning.setForeground(new java.awt.Color(255, 0, 0));

        loginbutton.setBackground(new java.awt.Color(0, 110, 110));
        loginbutton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginbuttonFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                loginbuttonFocusLost(evt);
            }
        });
        loginbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginbuttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginbuttonMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginbuttonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginbuttonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginbuttonMouseEntered(evt);
            }
        });
        loginbutton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginbuttonKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                loginbuttonKeyReleased(evt);
            }
        });
        loginbutton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LOG IN");
        loginbutton.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttonIcon_login.png"))); // NOI18N
        loginbutton.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 20));

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addComponent(PassLebel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PErrorField, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LoginPanelLayout.createSequentialGroup()
                        .addComponent(UnameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                        .addComponent(UErrorField, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(UnameField)
                    .addComponent(PassField)
                    .addComponent(warning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(loginbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UErrorField, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(UnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PassLebel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PErrorField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(PassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(warning, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        UnameField.getAccessibleContext().setAccessibleName("");

        jLabel1.setBackground(new java.awt.Color(0, 51, 51));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jLabel1.setText("Sign In With Valid Account");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_login.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Only authorized persons can login!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleParent(PErrorField);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PassFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PassFieldKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            if(UnameField.getText().equals(""))
            UnameField.requestFocus();

            UErrorField.setText("");
            PErrorField.setText("");

            if( UnameField.getText().equals(""))
            UErrorField.setText("*");

            if(PassField.getText().equals(""))
            PErrorField.setText("*");

            if(PErrorField.getText().equals("") && !PassField.getText().equals(""))
            {
                if ( authentication_.authenticate(UnameField.getText(), PassField.getText()) )
                {
        
                         homeForm_.setVisible(true);
                            homeForm_.toFront();
                             this.setVisible(false);
            
                    }
                else{
                     UnameField.setText("");
                     PassField.setText("");
                     warning.setText("Invalid Username or Password!");
                      UnameField.requestFocus();
                 }         
            
            }
        }
    }//GEN-LAST:event_PassFieldKeyPressed

    private void PassFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassFieldActionPerformed

    private void UnameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UnameFieldKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            if(!UnameField.getText().equals("")){
                UErrorField.setText("");
                PassField.requestFocus(true);
            }
            if(UErrorField.getText().equals(""))
            PassField.requestFocus(true);

        }
    }//GEN-LAST:event_UnameFieldKeyPressed

    private void UnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnameFieldActionPerformed

    }//GEN-LAST:event_UnameFieldActionPerformed

    private void UnameFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UnameFieldMouseClicked
        if(UnameField.getText().equals("") && !PassField.getText().equals("") && !UErrorField.getText().equals(""))
        {
            PassField.setText("");
            UErrorField.setText("");
        }
    }//GEN-LAST:event_UnameFieldMouseClicked

    private void UnameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UnameFieldFocusGained
       
    }//GEN-LAST:event_UnameFieldFocusGained

    private void loginbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbuttonMouseEntered
        this.loginbutton.setBackground(new java.awt.Color(0,100,100));
        
    }//GEN-LAST:event_loginbuttonMouseEntered

    private void loginbuttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbuttonMouseReleased
        this.loginbutton.setBackground(new java.awt.Color(0,100,100));
    }//GEN-LAST:event_loginbuttonMouseReleased

    private void loginbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbuttonMouseExited
        this.loginbutton.setBackground(new java.awt.Color(0,120,120));
    }//GEN-LAST:event_loginbuttonMouseExited

    private void loginbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbuttonMousePressed
       this.loginbutton.setBackground(new java.awt.Color(0,80,80));
    }//GEN-LAST:event_loginbuttonMousePressed

    private void loginbuttonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginbuttonFocusGained
       this.loginbutton.setBorder(new LineBorder(java.awt.Color.white,1));
    }//GEN-LAST:event_loginbuttonFocusGained

    private void loginbuttonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginbuttonFocusLost
       this.loginbutton.setBackground(new java.awt.Color(0,120,120));
        this.loginbutton.setBorder(createEmptyBorder());
    }//GEN-LAST:event_loginbuttonFocusLost

    private void loginbuttonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginbuttonKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_SPACE || evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.loginbutton.setBackground(new java.awt.Color(0,80,80));
            
        }
    }//GEN-LAST:event_loginbuttonKeyPressed

    private void loginbuttonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginbuttonKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_SPACE || evt.getKeyCode() == KeyEvent.VK_ENTER){
            processLogin();
        }
    }//GEN-LAST:event_loginbuttonKeyReleased

    private void loginbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbuttonMouseClicked
        processLogin();
    }//GEN-LAST:event_loginbuttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Form_Login().setVisible(true);
                
            }
        });
    }
    
    private void processLogin(){
        
        if(UnameField.getText().equals(""))
        UnameField.requestFocus();

        UErrorField.setText("");
        PErrorField.setText("");

        if( UnameField.getText().equals("")){
            UErrorField.setText("*");
        }
        if(PassField.getText().equals(""))
        {
            PErrorField.setText("*");
            if(!UnameField.getText().equals(""))
            PassField.requestFocus(true);
        }

        if(PErrorField.getText().equals("") && !PassField.getText().equals("")){
      //  Rlogin.Run(UnameField , PassField , this.warning, e);
        if ( authentication_.authenticate(UnameField.getText(), PassField.getText()) ){
        
            homeForm_.setVisible(true);
            homeForm_.toFront();
            this.setVisible(false);
            
        }
        else{
            UnameField.setText("");
            PassField.setText("");
            warning.setText("Invalid Username or Password!");
            UnameField.requestFocus();
        }
        }
        else{
            if(UnameField.getText().equals(""))
            UnameField.requestFocus();
            else
            PassField.requestFocus(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JLabel PErrorField;
    private javax.swing.JPasswordField PassField;
    private javax.swing.JLabel PassLebel;
    private javax.swing.JLabel UErrorField;
    private javax.swing.JTextField UnameField;
    private javax.swing.JLabel UnameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel loginbutton;
    private javax.swing.JLabel warning;
    // End of variables declaration//GEN-END:variables

    private void setBackground(Color rgb) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
