/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JPanel;

/**
 *
 * @author DanBroz
 */
public class Form_Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Form_Home() {

        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.pack();
    }

    public JMenu getModuleMenu() {
        return this.moduleMenu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        canvas2 = new java.awt.Canvas();
        ParentPanel = new javax.swing.JPanel();
        BussinessPanel = new javax.swing.JPanel();
        customerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        EmpPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        BrndPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ItmPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        StrPanel = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        AccountsPanel = new javax.swing.JPanel();
        PayPanel = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        RecPanel = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        InvPanel = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        SalePurchasedPanel = new javax.swing.JPanel();
        SalesPanel = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        PurchasePanel = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        AddSalePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        AddPurchasePanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        BussinessSelector = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        AccountsSelector = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        SalePurchasedSelector = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        moduleMenu = new javax.swing.JMenu();
        CusItem = new javax.swing.JMenuItem();
        EmpItem = new javax.swing.JMenuItem();
        MillItem = new javax.swing.JMenuItem();
        ItItem = new javax.swing.JMenuItem();
        StoreItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        SalItem = new javax.swing.JMenuItem();
        PurItem = new javax.swing.JMenuItem();
        InvoiceItem = new javax.swing.JMenuItem();
        PayItem = new javax.swing.JMenuItem();
        RecItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        SignOutItem = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenu2.setText("jMenu2");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setBackground(new java.awt.Color(255, 255, 255));
        setType(java.awt.Window.Type.POPUP);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        ParentPanel.setLayout(new java.awt.CardLayout());

        BussinessPanel.setBackground(new java.awt.Color(255, 255, 255));

        customerPanel.setBackground(new java.awt.Color(255, 255, 255));
        customerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                customerPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                customerPanelMouseExited(evt);
            }
        });
        customerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_Customers.png"))); // NOI18N
        customerPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Customers");
        customerPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText(" Add or Remove Customers");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        customerPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, 20));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText(" Veiw customer details");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        customerPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, 20));

        EmpPanel.setBackground(new java.awt.Color(255, 255, 255));
        EmpPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmpPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EmpPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EmpPanelMouseExited(evt);
            }
        });
        EmpPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_Employees.png"))); // NOI18N
        EmpPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Employees");
        EmpPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 30));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText(" Add or Remove Employees");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        EmpPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, 20));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText(" Veiw Employee details");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        EmpPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, 20));

        BrndPanel.setBackground(new java.awt.Color(255, 255, 255));
        BrndPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BrndPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BrndPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BrndPanelMouseExited(evt);
            }
        });
        BrndPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_Brand.png"))); // NOI18N
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        BrndPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, -1, 90));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("Brands");
        BrndPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 30));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setText(" Add or Remove brands");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BrndPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, 20));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 102));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText(" Veiw Brand details");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        BrndPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, 20));

        ItmPanel.setBackground(new java.awt.Color(255, 255, 255));
        ItmPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItmPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ItmPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ItmPanelMouseExited(evt);
            }
        });
        ItmPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_Items.png"))); // NOI18N
        ItmPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 102));
        jLabel17.setText("Items");
        ItmPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 30));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 102));
        jLabel18.setText(" Add or Remove Items");
        jLabel18.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ItmPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, 20));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 102));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText(" Veiw Item details");
        jLabel19.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        ItmPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, 20));

        StrPanel.setBackground(new java.awt.Color(255, 255, 255));
        StrPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StrPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StrPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StrPanelMouseExited(evt);
            }
        });
        StrPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_Store.png"))); // NOI18N
        StrPanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 102, 102));
        jLabel21.setText("Store");
        StrPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 30));

        jLabel22.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 102, 102));
        jLabel22.setText(" Add or Remove Items");
        jLabel22.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        StrPanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, 20));

        jLabel23.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 102, 102));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText(" Veiw Item details");
        jLabel23.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        StrPanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, 20));

        javax.swing.GroupLayout BussinessPanelLayout = new javax.swing.GroupLayout(BussinessPanel);
        BussinessPanel.setLayout(BussinessPanelLayout);
        BussinessPanelLayout.setHorizontalGroup(
            BussinessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BussinessPanelLayout.createSequentialGroup()
                .addGroup(BussinessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BussinessPanelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(customerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BussinessPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(BussinessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmpPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BrndPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(BussinessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ItmPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addComponent(StrPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );
        BussinessPanelLayout.setVerticalGroup(
            BussinessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BussinessPanelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(BussinessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ItmPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BussinessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(StrPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BrndPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        ParentPanel.add(BussinessPanel, "card4");

        AccountsPanel.setBackground(new java.awt.Color(255, 255, 255));

        PayPanel.setBackground(new java.awt.Color(255, 255, 255));
        PayPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PayPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PayPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PayPanelMouseExited(evt);
            }
        });
        PayPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_Payables.png"))); // NOI18N
        PayPanel.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, -1));

        jLabel38.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 102, 102));
        jLabel38.setText("Payables");
        PayPanel.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, 30));

        jLabel39.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 102, 102));
        jLabel39.setText(" Add or Remove Customers");
        jLabel39.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        PayPanel.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, 20));

        jLabel40.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 102, 102));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText(" Veiw customer details");
        jLabel40.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PayPanel.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, 20));

        RecPanel.setBackground(new java.awt.Color(255, 255, 255));
        RecPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RecPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RecPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RecPanelMouseExited(evt);
            }
        });
        RecPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_Receivables.png"))); // NOI18N
        RecPanel.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel42.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 102, 102));
        jLabel42.setText("Receivables");
        RecPanel.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, 30));

        jLabel43.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 102, 102));
        jLabel43.setText(" Add or Remove Customers");
        jLabel43.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        RecPanel.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, 20));

        jLabel44.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 102, 102));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText(" Veiw customer details");
        jLabel44.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        RecPanel.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, 20));

        InvPanel.setBackground(new java.awt.Color(255, 255, 255));
        InvPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InvPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InvPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InvPanelMouseExited(evt);
            }
        });
        InvPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_Invoices.png"))); // NOI18N
        InvPanel.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel46.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 102, 102));
        jLabel46.setText("Invoives");
        InvPanel.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 30));

        jLabel47.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(0, 102, 102));
        jLabel47.setText(" Add or Remove Customers");
        jLabel47.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        InvPanel.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, 20));

        jLabel48.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 102, 102));
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText(" Veiw customer details");
        jLabel48.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        InvPanel.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, 20));

        javax.swing.GroupLayout AccountsPanelLayout = new javax.swing.GroupLayout(AccountsPanel);
        AccountsPanel.setLayout(AccountsPanelLayout);
        AccountsPanelLayout.setHorizontalGroup(
            AccountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountsPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(AccountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RecPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(InvPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addGap(51, 51, 51))
        );
        AccountsPanelLayout.setVerticalGroup(
            AccountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountsPanelLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(AccountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InvPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(RecPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        ParentPanel.add(AccountsPanel, "card3");

        SalePurchasedPanel.setBackground(new java.awt.Color(255, 255, 255));

        SalesPanel.setBackground(new java.awt.Color(255, 255, 255));
        SalesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalesPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalesPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalesPanelMouseExited(evt);
            }
        });
        SalesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_Sales.png"))); // NOI18N
        SalesPanel.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, -1));

        jLabel52.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(0, 102, 102));
        jLabel52.setText("Sales");
        SalesPanel.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, 30));

        jLabel53.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(0, 102, 102));
        jLabel53.setText("View sale details");
        jLabel53.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        SalesPanel.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, 20));

        PurchasePanel.setBackground(new java.awt.Color(255, 255, 255));
        PurchasePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PurchasePanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PurchasePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PurchasePanelMouseExited(evt);
            }
        });
        PurchasePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_Purchases.png"))); // NOI18N
        PurchasePanel.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, -1));

        jLabel55.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(0, 102, 102));
        jLabel55.setText("Purchases");
        PurchasePanel.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, 30));

        jLabel56.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(0, 102, 102));
        jLabel56.setText("View puchase details");
        jLabel56.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        PurchasePanel.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, 20));

        AddSalePanel.setBackground(new java.awt.Color(255, 255, 255));
        AddSalePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddSalePanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddSalePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddSalePanelMouseExited(evt);
            }
        });
        AddSalePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttonIcon_plus.png"))); // NOI18N
        AddSalePanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 30, 30));

        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_Sales.png"))); // NOI18N
        AddSalePanel.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, -1));

        jLabel58.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(0, 102, 102));
        jLabel58.setText("Add Sales");
        AddSalePanel.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, 30));

        jLabel59.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(0, 102, 102));
        jLabel59.setText("Create and Add new sales");
        jLabel59.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        AddSalePanel.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, 20));

        AddPurchasePanel.setBackground(new java.awt.Color(255, 255, 255));
        AddPurchasePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddPurchasePanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddPurchasePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddPurchasePanelMouseExited(evt);
            }
        });
        AddPurchasePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttonIcon_plus.png"))); // NOI18N
        AddPurchasePanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 30, 30));

        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_Purchases.png"))); // NOI18N
        AddPurchasePanel.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, -1));

        jLabel61.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(0, 102, 102));
        jLabel61.setText("Add Purchases");
        AddPurchasePanel.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, 30));

        jLabel62.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(0, 102, 102));
        jLabel62.setText("Create and Add new Purchases");
        jLabel62.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        AddPurchasePanel.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, 20));

        javax.swing.GroupLayout SalePurchasedPanelLayout = new javax.swing.GroupLayout(SalePurchasedPanel);
        SalePurchasedPanel.setLayout(SalePurchasedPanelLayout);
        SalePurchasedPanelLayout.setHorizontalGroup(
            SalePurchasedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SalePurchasedPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(SalePurchasedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SalesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddSalePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(SalePurchasedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SalePurchasedPanelLayout.createSequentialGroup()
                        .addComponent(PurchasePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addComponent(AddPurchasePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        SalePurchasedPanelLayout.setVerticalGroup(
            SalePurchasedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SalePurchasedPanelLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(SalePurchasedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PurchasePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SalesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(SalePurchasedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddSalePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddPurchasePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        ParentPanel.add(SalePurchasedPanel, "card4");

        BussinessSelector.setBackground(new java.awt.Color(0, 150, 150));
        BussinessSelector.setToolTipText("");
        BussinessSelector.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BussinessSelectorMouseClicked(evt);
            }
        });
        BussinessSelector.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Bussiness");
        BussinessSelector.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 20));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_bussiness.png"))); // NOI18N
        BussinessSelector.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 40));

        AccountsSelector.setBackground(new java.awt.Color(0, 125, 125));
        AccountsSelector.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountsSelectorMouseClicked(evt);
            }
        });
        AccountsSelector.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Accounts");
        AccountsSelector.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 20));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_accounts.png"))); // NOI18N
        AccountsSelector.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        SalePurchasedSelector.setBackground(new java.awt.Color(0, 125, 125));
        SalePurchasedSelector.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalePurchasedSelectorMouseClicked(evt);
            }
        });
        SalePurchasedSelector.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Sales/Purchases");
        SalePurchasedSelector.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 20));

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_accounts.png"))); // NOI18N
        SalePurchasedSelector.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BussinessSelector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AccountsSelector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SalePurchasedSelector, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ParentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(canvas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ParentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(canvas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(BussinessSelector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SalePurchasedSelector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AccountsSelector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(143, 143, 143))
        );

        jMenuBar1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jMenuBar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuBar1MouseClicked(evt);
            }
        });
        jMenuBar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenuBar1KeyPressed(evt);
            }
        });

        moduleMenu.setText("Modules");
        moduleMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        moduleMenu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                moduleMenuKeyPressed(evt);
            }
        });

        CusItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        CusItem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CusItem.setText("Customers");
        CusItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CusItemActionPerformed(evt);
            }
        });
        moduleMenu.add(CusItem);

        EmpItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        EmpItem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EmpItem.setText("Employees");
        EmpItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpItemActionPerformed(evt);
            }
        });
        moduleMenu.add(EmpItem);

        MillItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        MillItem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MillItem.setText("Brands");
        MillItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MillItemActionPerformed(evt);
            }
        });
        moduleMenu.add(MillItem);

        ItItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        ItItem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ItItem.setText("Items");
        ItItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItItemActionPerformed(evt);
            }
        });
        moduleMenu.add(ItItem);

        StoreItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK));
        StoreItem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        StoreItem.setText("Store");
        StoreItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StoreItemActionPerformed(evt);
            }
        });
        moduleMenu.add(StoreItem);
        moduleMenu.add(jSeparator2);

        SalItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        SalItem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SalItem.setText("Sale Invoice");
        SalItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalItemActionPerformed(evt);
            }
        });
        moduleMenu.add(SalItem);

        PurItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        PurItem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PurItem.setText("Purchase Invoice");
        PurItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PurItemActionPerformed(evt);
            }
        });
        moduleMenu.add(PurItem);

        InvoiceItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK));
        InvoiceItem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        InvoiceItem.setText("Credit Invoices");
        InvoiceItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InvoiceItemActionPerformed(evt);
            }
        });
        moduleMenu.add(InvoiceItem);

        PayItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        PayItem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PayItem.setText("Payables");
        PayItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayItemActionPerformed(evt);
            }
        });
        moduleMenu.add(PayItem);

        RecItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        RecItem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RecItem.setText("Receivables");
        RecItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecItemActionPerformed(evt);
            }
        });
        moduleMenu.add(RecItem);
        moduleMenu.add(jSeparator1);

        SignOutItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        SignOutItem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SignOutItem.setForeground(new java.awt.Color(255, 0, 0));
        SignOutItem.setText("Sign out");
        SignOutItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignOutItemActionPerformed(evt);
            }
        });
        moduleMenu.add(SignOutItem);

        jMenuBar1.add(moduleMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void changePanel(JPanel newPanel) {
        this.ParentPanel.removeAll();
        this.ParentPanel.add(newPanel);
        this.ParentPanel.repaint();
        this.ParentPanel.revalidate();
    }

    private void SignOutItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignOutItemActionPerformed
        new Form_Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SignOutItemActionPerformed

    private void SalItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalItemActionPerformed
        new Form_SaleInvoice().setVisible(true);
    }//GEN-LAST:event_SalItemActionPerformed

    private void InvoiceItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InvoiceItemActionPerformed
        new Form_CreditInvoice().setVisible(true);
    }//GEN-LAST:event_InvoiceItemActionPerformed

    private void EmpItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpItemActionPerformed
        new Form_Employees(this.EmpItem).setVisible(true);
    }//GEN-LAST:event_EmpItemActionPerformed

    private void PurItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PurItemActionPerformed
        new Form_PurchaseInvoice().setVisible(true);
    }//GEN-LAST:event_PurItemActionPerformed

    private void MillItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MillItemActionPerformed
        new Form_Brands(this.MillItem).setVisible(true);
    }//GEN-LAST:event_MillItemActionPerformed

    private void moduleMenuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_moduleMenuKeyPressed

    }//GEN-LAST:event_moduleMenuKeyPressed

    private void jMenuBar1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuBar1KeyPressed

    }//GEN-LAST:event_jMenuBar1KeyPressed

    private void jMenuBar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar1MouseClicked

    }//GEN-LAST:event_jMenuBar1MouseClicked

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed

    }//GEN-LAST:event_jPanel1KeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

    }//GEN-LAST:event_formKeyPressed

    private void ItItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItItemActionPerformed
        new Form_Items(this.ItItem).setVisible(true);
    }//GEN-LAST:event_ItItemActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void RecItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecItemActionPerformed
        new Form_Receivables(this.RecItem).setVisible(true);
    }//GEN-LAST:event_RecItemActionPerformed

    private void PayItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayItemActionPerformed
        new Form_Payables(this.PayItem).setVisible(true);
    }//GEN-LAST:event_PayItemActionPerformed

    private void StoreItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StoreItemActionPerformed
        new Form_Store(this.StoreItem).setVisible(true);
    }//GEN-LAST:event_StoreItemActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
    }//GEN-LAST:event_formWindowStateChanged

    private void customerPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerPanelMouseClicked
        new Form_Customers(this).setVisible(true);
    }//GEN-LAST:event_customerPanelMouseClicked

    private void customerPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerPanelMouseEntered
        this.customerPanel.setBackground(new Color(153, 230, 250));
    }//GEN-LAST:event_customerPanelMouseEntered

    private void customerPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerPanelMouseExited
        this.customerPanel.setBackground(new Color(255, 255, 255));
    }
//        this.cusPanel.setBackground(new Color(0,153,153));    }//GEN-LAST:event_customerPanelMouseExited
    private void EmpPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpPanelMouseClicked
        new Form_Employees(this.EmpItem).setVisible(true);
    }//GEN-LAST:event_EmpPanelMouseClicked

    private void EmpPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpPanelMouseEntered
        this.EmpPanel.setBackground(new Color(153, 230, 250));
    }//GEN-LAST:event_EmpPanelMouseEntered

    private void EmpPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpPanelMouseExited
        this.EmpPanel.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_EmpPanelMouseExited

    private void BrndPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BrndPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BrndPanelMouseClicked

    private void BrndPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BrndPanelMouseEntered
        this.BrndPanel.setBackground(new Color(153, 230, 250));
    }//GEN-LAST:event_BrndPanelMouseEntered

    private void BrndPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BrndPanelMouseExited
        this.BrndPanel.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_BrndPanelMouseExited

    private void ItmPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItmPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ItmPanelMouseClicked

    private void ItmPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItmPanelMouseEntered
        this.ItmPanel.setBackground(new Color(153, 230, 250));
    }//GEN-LAST:event_ItmPanelMouseEntered

    private void ItmPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItmPanelMouseExited
        this.ItmPanel.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_ItmPanelMouseExited

    private void StrPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StrPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_StrPanelMouseClicked

    private void StrPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StrPanelMouseEntered
        this.StrPanel.setBackground(new Color(153, 230, 250));
    }//GEN-LAST:event_StrPanelMouseEntered

    private void StrPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StrPanelMouseExited
        this.StrPanel.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_StrPanelMouseExited

    private void CusItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CusItemActionPerformed
        new Form_Customers(this).setVisible(true);
    }//GEN-LAST:event_CusItemActionPerformed

    private void AccountsSelectorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountsSelectorMouseClicked
        changePanel(this.AccountsPanel);
        this.BussinessSelector.setBackground(new Color(0, 125, 125));
        this.SalePurchasedSelector.setBackground(new Color(0, 125, 125));
        this.AccountsSelector.setBackground(new Color(0, 150, 150));
    }//GEN-LAST:event_AccountsSelectorMouseClicked

    private void BussinessSelectorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BussinessSelectorMouseClicked
        changePanel(this.BussinessPanel);
        this.AccountsSelector.setBackground(new Color(0, 125, 125));
        this.SalePurchasedSelector.setBackground(new Color(0, 125, 125));
        this.BussinessSelector.setBackground(new Color(0, 150, 150));
    }//GEN-LAST:event_BussinessSelectorMouseClicked

    private void PayPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PayPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PayPanelMouseClicked

    private void PayPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PayPanelMouseEntered
        this.PayPanel.setBackground(new Color(153, 230, 250));
    }//GEN-LAST:event_PayPanelMouseEntered

    private void PayPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PayPanelMouseExited
        this.PayPanel.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_PayPanelMouseExited

    private void RecPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RecPanelMouseClicked

    private void RecPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecPanelMouseEntered
        this.RecPanel.setBackground(new Color(153, 230, 250));
    }//GEN-LAST:event_RecPanelMouseEntered

    private void RecPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecPanelMouseExited
        this.RecPanel.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_RecPanelMouseExited

    private void InvPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_InvPanelMouseClicked

    private void InvPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvPanelMouseEntered
        this.InvPanel.setBackground(new Color(153, 230, 250));
    }//GEN-LAST:event_InvPanelMouseEntered

    private void InvPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvPanelMouseExited
        this.InvPanel.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_InvPanelMouseExited

    private void SalePurchasedSelectorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalePurchasedSelectorMouseClicked
        changePanel(this.SalePurchasedPanel);
        this.AccountsSelector.setBackground(new Color(0, 125, 125));
        this.BussinessSelector.setBackground(new Color(0, 125, 125));
        this.SalePurchasedSelector.setBackground(new Color(0, 150, 150));
    }//GEN-LAST:event_SalePurchasedSelectorMouseClicked

    private void SalesPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalesPanelMouseClicked
        new Form_Sales(this.SalItem).setVisible(true);
    }//GEN-LAST:event_SalesPanelMouseClicked

    private void SalesPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalesPanelMouseEntered
        this.SalesPanel.setBackground(new Color(153, 230, 250));
    }//GEN-LAST:event_SalesPanelMouseEntered

    private void SalesPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalesPanelMouseExited
        this.SalesPanel.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_SalesPanelMouseExited

    private void PurchasePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PurchasePanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PurchasePanelMouseClicked

    private void PurchasePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PurchasePanelMouseEntered
        this.PurchasePanel.setBackground(new Color(153, 230, 250));
    }//GEN-LAST:event_PurchasePanelMouseEntered

    private void PurchasePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PurchasePanelMouseExited
        this.PurchasePanel.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_PurchasePanelMouseExited

    private void AddSalePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddSalePanelMouseClicked
        new Form_SaleInvoice().setVisible(true);
    }//GEN-LAST:event_AddSalePanelMouseClicked

    private void AddSalePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddSalePanelMouseEntered
        this.AddSalePanel.setBackground(new Color(153, 230, 250));
    }//GEN-LAST:event_AddSalePanelMouseEntered

    private void AddSalePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddSalePanelMouseExited
        this.AddSalePanel.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_AddSalePanelMouseExited

    private void AddPurchasePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddPurchasePanelMouseClicked
        // TODO add your handling code here:
        new Form_PurchaseInvoice().setVisible(true);
    }//GEN-LAST:event_AddPurchasePanelMouseClicked

    private void AddPurchasePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddPurchasePanelMouseEntered
        this.AddPurchasePanel.setBackground(new Color(153, 230, 250));
    }//GEN-LAST:event_AddPurchasePanelMouseEntered

    private void AddPurchasePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddPurchasePanelMouseExited
        this.AddPurchasePanel.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_AddPurchasePanelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccountsPanel;
    private javax.swing.JPanel AccountsSelector;
    private javax.swing.JPanel AddPurchasePanel;
    private javax.swing.JPanel AddSalePanel;
    private javax.swing.JPanel BrndPanel;
    private javax.swing.JPanel BussinessPanel;
    private javax.swing.JPanel BussinessSelector;
    private javax.swing.JMenuItem CusItem;
    private javax.swing.JMenuItem EmpItem;
    private javax.swing.JPanel EmpPanel;
    private javax.swing.JPanel InvPanel;
    private javax.swing.JMenuItem InvoiceItem;
    private javax.swing.JMenuItem ItItem;
    private javax.swing.JPanel ItmPanel;
    private javax.swing.JMenuItem MillItem;
    private javax.swing.JPanel ParentPanel;
    private javax.swing.JMenuItem PayItem;
    private javax.swing.JPanel PayPanel;
    private javax.swing.JMenuItem PurItem;
    private javax.swing.JPanel PurchasePanel;
    private javax.swing.JMenuItem RecItem;
    private javax.swing.JPanel RecPanel;
    private javax.swing.JMenuItem SalItem;
    private javax.swing.JPanel SalePurchasedPanel;
    private javax.swing.JPanel SalePurchasedSelector;
    private javax.swing.JPanel SalesPanel;
    private javax.swing.JMenuItem SignOutItem;
    private javax.swing.JMenuItem StoreItem;
    private javax.swing.JPanel StrPanel;
    private java.awt.Canvas canvas2;
    private javax.swing.JPanel customerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu moduleMenu;
    // End of variables declaration//GEN-END:variables
}
